7589 create cassandra monitoring metrics
insightfinder/InsightAgent pull request #288
Opened 2020-10-19 08:56 UTC by bdulive

2020-10-21 16:13 UTC, yqian10 commented on jolokia-cassandra-stream/getmetrics_jolokia.py
> +    path_vals = full_path.split(",")
please use uppercase parameter for constant like you did in line 11 and 12

2020-10-21 16:18 UTC, yqian10 commented on jolokia-cassandra-stream/getmetrics_jolokia.py
> +            #file_name = parser.get('InsightFinder', 'file_name')
if you do not support file, please remove it in both code and config file rather than comment

2020-10-21 16:18 UTC, yqian10 commented on jolokia-cassandra-stream/getmetrics_jolokia.py
> +#    'org.apache.cassandra.metrics:name=TotalLatency,scope=Read,type=ClientRequest': ['Count'],
please remove commented code if you do not need them

2020-10-21 16:19 UTC, yqian10 requested changes
constant

2020-10-21 21:40 UTC, dearmore approved these changes

2020-10-22 13:33 UTC, yqian10 approved these changes

2020-10-22 17:42 UTC, dearmore approved these changes

2020-10-22 17:43 UTC, merged